[package]
name = "tracing-ext-ffi-subscriber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12"
tracing = "0.1"

[build-dependencies]
cbindgen = "0.23"
